const QUESTIONS = [
  { id: 'q1', category: 'Naturaleza', text: '¿Qué cordillera atraviesa el oeste de San Juan?', hint: 'Marca el límite con Chile.', answers: [{ id: 'a', text: 'Cordillera de los Andes' }, { id: 'b', text: 'Sierras Pampeanas' }, { id: 'c', text: 'Cordillera del Viento' }, { id: 'd', text: 'Sierra de la Ventana' }], correctAnswer: 'a', explanation: 'La cordillera de los Andes recorre el oeste argentino y forma parte del límite natural con Chile.' },
  { id: 'q2', category: 'Paisajes', text: '¿En qué departamento se encuentra el Parque Provincial Ischigualasto?', hint: 'También es conocido como Valle de la Luna.', answers: [{ id: 'a', text: 'Calingasta' }, { id: 'b', text: 'Valle Fértil' }, { id: 'c', text: 'Iglesia' }, { id: 'd', text: 'Zonda' }], correctAnswer: 'b', explanation: 'Ischigualasto se encuentra en el departamento Valle Fértil y es famoso por su paisaje geológico.' },
  { id: 'q3', category: 'Historia', text: '¿Qué prócer fue gobernador de Cuyo y cruzó los Andes?', hint: 'Su nombre está ligado a la independencia americana.', answers: [{ id: 'a', text: 'Manuel Belgrano' }, { id: 'b', text: 'Martín Miguel de Güemes' }, { id: 'c', text: 'José de San Martín' }, { id: 'd', text: 'Juan Bautista Alberdi' }], correctAnswer: 'c', explanation: 'José de San Martín fue gobernador de Cuyo y organizó el Ejército de los Andes.' },
  { id: 'q4', category: 'Sabores', text: '¿Qué cultivo es central en la producción vitivinícola sanjuanina?', hint: 'Su fruto se transforma en vino.', answers: [{ id: 'a', text: 'La vid' }, { id: 'b', text: 'El olivo' }, { id: 'c', text: 'El nogal' }, { id: 'd', text: 'El algodón' }], correctAnswer: 'a', explanation: 'La vid es la planta que produce uvas, materia prima de una importante actividad vitivinícola.' },
  { id: 'q5', category: 'Astronomía', text: '¿Por qué San Juan es una provincia elegida para observar el cielo?', hint: 'Pensá en sus noches y su clima seco.', answers: [{ id: 'a', text: 'Por sus frecuentes lluvias' }, { id: 'b', text: 'Por su aire seco y cielos despejados' }, { id: 'c', text: 'Por estar junto al mar' }, { id: 'd', text: 'Por sus bosques tropicales' }], correctAnswer: 'b', explanation: 'El clima seco y muchos días despejados favorecen la observación astronómica.' },
  { id: 'q6', category: 'Geografía', text: '¿Qué río da nombre al dique más conocido junto a la ciudad de San Juan?', hint: 'El dique comparte su nombre con el río.', answers: [{ id: 'a', text: 'Río Jáchal' }, { id: 'b', text: 'Río San Juan' }, { id: 'c', text: 'Río Bermejo' }, { id: 'd', text: 'Río Desaguadero' }], correctAnswer: 'b', explanation: 'El dique y el río San Juan son piezas importantes del paisaje y del aprovechamiento hídrico provincial.' },
  { id: 'q7', category: 'Tradiciones', text: '¿Qué fiesta nacional se celebra en San Juan alrededor de la vendimia?', hint: 'Reconoce el trabajo de quienes producen uvas.', answers: [{ id: 'a', text: 'Fiesta Nacional del Sol' }, { id: 'b', text: 'Fiesta Nacional de la Vendimia' }, { id: 'c', text: 'Fiesta del Chamamé' }, { id: 'd', text: 'Fiesta de la Nieve' }], correctAnswer: 'a', explanation: 'La Fiesta Nacional del Sol es una celebración emblemática de la identidad sanjuanina.' },
  { id: 'q8', category: 'Aventura', text: '¿Qué actividad es popular en los diques y embalses sanjuaninos?', hint: 'Se practica sobre el agua.', answers: [{ id: 'a', text: 'Esquí acuático' }, { id: 'b', text: 'Buceo en arrecifes' }, { id: 'c', text: 'Surf oceánico' }, { id: 'd', text: 'Pesca en hielo' }], correctAnswer: 'a', explanation: 'Los espejos de agua de la provincia permiten realizar deportes náuticos como el esquí acuático.' },
  { id: 'q9', category: 'Paleontología', text: '¿Qué tipo de hallazgos hicieron famoso a Ischigualasto?', hint: 'Son restos de seres muy antiguos.', answers: [{ id: 'a', text: 'Restos de dinosaurios' }, { id: 'b', text: 'Barcos coloniales' }, { id: 'c', text: 'Glaciares activos' }, { id: 'd', text: 'Arrecifes de coral' }], correctAnswer: 'a', explanation: 'En Ischigualasto se hallaron fósiles fundamentales para estudiar los primeros dinosaurios.' },
  { id: 'q10', category: 'Geografía', text: '¿Cuál de estos departamentos sanjuaninos es reconocido por su paisaje cordillerano?', hint: 'Está en el noroeste provincial.', answers: [{ id: 'a', text: 'Iglesia' }, { id: 'b', text: 'Rawson' }, { id: 'c', text: 'Capital' }, { id: 'd', text: 'Santa Lucía' }], correctAnswer: 'a', explanation: 'Iglesia reúne paisajes de montaña y es una puerta de entrada a la cordillera sanjuanina.' },
  { id: 'q11', category: 'Naturaleza', text: '¿Cómo se llama la reserva donde se protege el guanaco y la fauna del monte?', hint: 'Está cerca de la capital.', answers: [{ id: 'a', text: 'Loma de Las Tapias' }, { id: 'b', text: 'Talampaya' }, { id: 'c', text: 'El Palmar' }, { id: 'd', text: 'Iberá' }], correctAnswer: 'a', explanation: 'La reserva Loma de Las Tapias conserva ambientes de monte característicos de la región.' },
  { id: 'q12', category: 'Sabores', text: 'Además del vino, ¿qué producto de la uva se elabora tradicionalmente en San Juan?', hint: 'Es una fruta deshidratada.', answers: [{ id: 'a', text: 'Pasas de uva' }, { id: 'b', text: 'Mermelada de naranja' }, { id: 'c', text: 'Té negro' }, { id: 'd', text: 'Chocolate' }], correctAnswer: 'a', explanation: 'Las pasas de uva son parte de la producción vinculada al cultivo de la vid.' },
  { id: 'q13', category: 'Paisajes', text: '¿Qué tono predomina en los cerros del Valle de la Luna?', hint: 'Es un paisaje de rocas y sedimentos.', answers: [{ id: 'a', text: 'Grises y ocres' }, { id: 'b', text: 'Verde intenso' }, { id: 'c', text: 'Azul marino' }, { id: 'd', text: 'Blanco nevado todo el año' }], correctAnswer: 'a', explanation: 'Las formaciones sedimentarias de Ischigualasto muestran una paleta de tonos grises, ocres y rojizos.' },
  { id: 'q14', category: 'Historia', text: '¿En qué siglo ocurrió el terremoto que marcó profundamente a la ciudad de San Juan?', hint: 'Ocurrió durante la década de 1940.', answers: [{ id: 'a', text: 'Siglo XVIII' }, { id: 'b', text: 'Siglo XIX' }, { id: 'c', text: 'Siglo XX' }, { id: 'd', text: 'Siglo XXI' }], correctAnswer: 'c', explanation: 'El terremoto de 1944 transformó la ciudad y marcó la historia contemporánea de la provincia.' },
  { id: 'q15', category: 'Aventura', text: '¿Qué elemento natural aprovecha el carrovelismo en la Pampa del Leoncito?', hint: 'Es invisible, pero impulsa la vela.', answers: [{ id: 'a', text: 'El viento' }, { id: 'b', text: 'La corriente marina' }, { id: 'c', text: 'El vapor' }, { id: 'd', text: 'La electricidad' }], correctAnswer: 'a', explanation: 'El viento constante hace de la Pampa del Leoncito un lugar reconocido para el carrovelismo.' }
];
